### ISSUE TITLE
No such file or directoy

### ISSUE THREAD

**Issue by Lazyshot** [nathanmarz/storm-deploy#1]
The following error was found when deploying the default configuration.

The exact timing is right after it installs jzmq, then the following lines print after "INVOKE make (install)":

> WARN  deprecate - DEPRECATED [backtype/storm/crate/storm.clj:94] pallet.resource.exec-script/exec-checked-script is deprecated, use pallet.action.exec-script/exec-checked-script
> WARN  deprecate - DEPRECATED [backtype/storm/crate/storm.clj:89] pallet.resource.exec-script/exec-checked-script is deprecated, use pallet.action.exec-script/exec-checked-script
> Exception in thread "main" java.io.FileNotFoundException: /Users/nathan/.ssh/storm (No such file or directory) (NO_SOURCE_FILE:1)
> ........
>   at clojure.java.io$reader.doInvoke(io.clj:96)
>   at clojure.lang.RestFn.invoke(RestFn.java:411)
>   at clojure.lang.AFn.applyToHelper(AFn.java:163)
>   at clojure.lang.RestFn.applyTo(RestFn.java:133)
>   at clojure.core$apply.invoke(core.clj:542)
>   at clojure.core$slurp.doInvoke(core.clj:5372)
>   at clojure.lang.RestFn.invoke(RestFn.java:411)
>   at backtype.storm.crate.storm$install_github_key.invoke(storm.clj:40)
>   at backtype.storm.crate.storm$make.invoke(storm.clj:88)
>   at backtype.storm.crate.storm$install_supervisor.invoke(storm.clj:109)
>   at backtype.storm.node$supervisor_server_spec$fn__8573.invoke(node.clj:96)

**Comment by nathanmarz** [comment]
Oops, the deploy was still assuming Storm was a private repo. I updated it and it should work now.
