### ISSUE TITLE
AWS region seems to be ignored when creating instances

### ISSUE THREAD

**Issue by jatrost** [nathanmarz/storm-deploy#2]
I tried setting the "jclouds.regions" to "us-west-1" in ~/.pallet/config.clj and when I ran the deploy start cluster command instances were started in us-east-1. Not sure if this is a bug in storm-deploy, jclouds, or pallet...

**Comment by jasonjckn** [comment]
To use us-west-1 you need to change all the image id's in conf/clusters.yaml 

You must find a new AMI for us-west-1. This should work "us-west-1/ami-a17e2ee4". (from alestic.com)

You can update the jclouds.regions string too. That entire line can actually be removed afaik. It's just a jclouds optimization.

**Comment by jasonjckn** [comment]
If it works without jclouds.regions setting let me know and i'll remove it from example config.clj

**Comment by nathanmarz** [comment]
The deploy uses jclouds.regions for setting up security permissions, so can't remove that.
