### ISSUE TITLE
public-key-path in ~/.pallet/config.clj seems to be ignored

### ISSUE THREAD

**Issue by jatrost** [nathanmarz/storm-deploy#3]
I have ssh keys that may be named a little non standard (e.g. key.pem and key.pub) and when I setup my ~/.pallet/config.clj with the full path to these keys there was a FileNotFoundException because it could not find "key.pem.pub".  It seems that the public-key-path is not used and the private key name + ".pub" is used instead.  I was able to get this working by creating a soft link from key.pub to key.pem.pub, but this seems to be a bug.  I am not sure if this is a bug in storm-deploy, pallet, or jclouds...

**Comment by lorcan** [comment]
Yes, this is a pallet problem. 
From the requirements [in the wiki](https://github.com/nathanmarz/storm-deploy/wiki):

> Public and private key paths for setting up ssh on the nodes. The public key path must be the private key path + ".pub" (this seems to be a bug in pallet). On Linux, you should have a null passphrase on the keys.

I'd suggest we close this issue.

**Comment by jasonjckn** [comment]
upgraded to pallet 0.7.3, this should be fixed.
