### ISSUE TITLE
`lein deploy-storm` stalls

### ISSUE THREAD

**Issue by xpe** [nathanmarz/storm-deploy#37]
The `lein deploy-storm ...` command "stalls" towards the end.

After showing the following messages, it isn't doing much. I don't know if I should kill it.

Is this a bug in `lein deploy-storm`?

```
lein deploy-storm --start --name my-cluster --release 0.8.2

...

DEBUG compute - >> listing node details matching(ALWAYS_TRUE)
DEBUG compute - << list(5)
DEBUG compute - >> listing node details matching(ALWAYS_TRUE)
DEBUG compute - << list(5)
DEBUG compute - >> listing node details matching(ALWAYS_TRUE)
DEBUG compute - << list(5)
DEBUG compute - >> listing node details matching(ALWAYS_TRUE)
DEBUG compute - << list(5)
INFO  provision - Attaching Complete.
INFO  provision - Provisioning Complete.
DEBUG compute - >> listing node details matching(ALWAYS_TRUE)
DEBUG compute - << list(5)
INFO  provision - TAG:     zookeeper-my-cluster
INFO  provision - PUBLIC:  23.99.9.999
INFO  provision - PRIVATE: 10.99.999.9
DEBUG compute - >> listing node details matching(ALWAYS_TRUE)
DEBUG compute - << list(5)
INFO  provision - TAG:     nimbus-my-cluster
INFO  provision - PUBLIC:  54.999.9.999
INFO  provision - PRIVATE: 10.999.999.99
DEBUG compute - >> listing node details matching(ALWAYS_TRUE)
DEBUG compute - << list(5)
INFO  provision - TAG:     supervisor-my-cluster
INFO  provision - PUBLIC:  184.99.999.999, 23.99.999.99
INFO  provision - PRIVATE: 10.99.999.999, 10.999.999.999
```

**Comment by gworley3** [comment]
I also frequently see this issue. I haven't investigated what the cause is but just killing the process seems to be fine so long as you wait until it gets to this point and is at the real end, so that workaround should be fine in the mean time. However I agree that it's a bug.

**Comment by tbatchelli** [comment]
It seems to be some issue with leiningen. We could call System.exit() at the end to force it to quit, but I don't think this is a good solution. I am investigating.

Toni.

On Jul 13, 2013, at 6:33 AM, G Gordon Worley III notifications@github.com wrote:

> I also frequently see this issue. I haven't investigated what the cause is but just killing the process seems to be fine so long as you wait until it gets to this point and is at the real end, so that workaround should be fine in the mean time. However I agree that it's a bug.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Antoni Batchelli
Founder palletops.com
- twitter: @tbatchelli , @disclojure
  --- email: tbatchelli@gmail.com
  ----- web: tbatchelli.org , disclojure.org
