### ISSUE TITLE
Windows Cygwin

### ISSUE THREAD

**Issue by pherris** [nathanmarz/storm-deploy#38]
Ran into a couple of issues using Cygwin. I had to run:

```
eval `ssh-agent`
```

to enable ssh to the instances that were started.

Had to install pageant.exe:

http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html

to get past the error:

```
Could not initialize class com.jcraft.jsch.agentproxy.usocket.JNAUSocketFactory$CLibrary
```

thx to: http://logs.lazybot.org/irc.freenode.net/%23pallet/2013-04-11.txt

I also ran into the "Security Group Does Not Exist" error but haven't worked through that one yet.

Hope this helps someone else...

**Comment by guarly** [comment]
Hi,

There is a pull request from my email to solve the security error. You may
give it a try.

**Comment by pherris** [comment]
Thanks, that solved it for me.
