### ISSUE TITLE
Could not find artifact org.clojure:clojure-contrib

### ISSUE THREAD

**Issue by FergusNelson** [nathanmarz/storm-deploy#41]
I get the following error when running lein deps

Could not find artifact org.clojure:clojure-contrib:pom:1.1.0 in central (http://repo1.maven.org/maven2)
Could not find artifact org.clojure:clojure-contrib:pom:1.1.0 in clojars (https://clojars.org/repo/)
Could not find artifact org.clojure:clojure-contrib:pom:1.1.0 in jclouds-snapshot (https://oss.sonatype.org/content/repositories/snapshots)
Could not find artifact org.clojure:clojure-contrib:pom:1.1.0 in sonatype (https://oss.sonatype.org/content/repositories/releases)
Could not transfer artifact org.clojure:clojure-contrib:pom:1.1.0 from/to sonatype-nexus-releases (http://oss.sonatype.org/content/repositories/releases): Connection to http://oss.sonatype.org refused
Could not transfer artifact org.clojure:clojure-contrib:pom:1.1.0 from/to clojure (http://build.clojure.org/releases): Connection to http://build.clojure.org refused
Could not transfer artifact org.clojure:clojure-contrib:pom:1.1.0 from/to clojure-snapshots (http://build.clojure.org/snapshots): Connection to http://build.clojure.org refused
Check :dependencies and :repositories for typos.
It's possible the specified jar is not in any repository.
If so, see "Free-floating Jars" under http://j.mp/repeatability

**Comment by FergusNelson** [comment]
Appears to be related to how clojure-contrib has been split up http://dev.clojure.org/display/community/Where+Did+Clojure.Contrib+Go

**Comment by FergusNelson** [comment]
Work around was to manually grab the bits from https://code.google.com/p/clojure-contrib/downloads/list and manually install into your local maven repo.

**Comment by arohner** [comment]
(Complete bystander, I found this issue when googling for a similar problem). I was able to fix it by adding http://build.clojure.org/releases/ to my maven repos.

**Comment by tbatchelli** [comment]
Closing: Contrib was returned to its original location by its owners.
