### ISSUE TITLE
Unable to sudo

### ISSUE THREAD

**Issue by spisarski** [nathanmarz/storm-deploy#53]
The VMs generated by when running storm-deploy are not allowing for "sudo" access but have no problems with this when creating one manually.  "sudo" is required to check the logs as I can access Ganglia on port 80 but not the Storm UI (8080) and all daemon process appear to be running.

**Comment by tbatchelli** [comment]
Hi, I tried to reproduce your issue, which I understand is that you cannot sudo after deploying storm on some EC2 nodes, but I am able to sudo as the text below shows.

```
[~] ➔ ssh storm@54.227.25.117
Welcome to Ubuntu 12.04.1 LTS (GNU/Linux 3.2.0-35-virtual x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Wed Jan  8 21:12:44 UTC 2014

  System load:  0.48              Processes:           67
  Usage of /:   14.0% of 9.84GB   Users logged in:     0
  Memory usage: 7%                IP address for eth0: 10.110.65.195
  Swap usage:   0%

  Graph this data and manage this system at https://landscape.canonical.com/

Get cloud support with Ubuntu Advantage Cloud Guest
  http://www.ubuntu.com/business/services/cloud
Last login: Wed Jan  8 20:50:28 2014 from 208.90.214.44
storm@ip-10-110-65-195:~$ sudo su -
root@ip-10-110-65-195:~# exit
logout
storm@ip-10-110-65-195:~$ sudo su
root@ip-10-110-65-195:/home/storm# exit
exit
storm@ip-10-110-65-195:~$ 
```

Is this issue still happening for you?

**Comment by spisarski** [comment]
Thanks very much!  I was using the user "ubuntu" instead of "storm".  I'll create a new issue should I still have problems accessing the storm UI.
