### ISSUE TITLE
zookeeper 3.3.3 is no longer available

### ISSUE THREAD

**Issue by okapies** [nathanmarz/storm-deploy#9]
`lein run :deploy --start` will fail because apache project removes old versions of zookeeper from their server.

http://www.apache.org/dist/zookeeper/zookeeper-3.3.3/zookeeper-3.3.3.tar.gz

The version number (3.3.3) is hard-coded in the following:

https://github.com/nathanmarz/storm-deploy/blob/master/src/clj/backtype/storm/node.clj#L76
https://github.com/nathanmarz/storm-deploy/blob/master/src/clj/backtype/storm/crate/zookeeper.clj#L49

**Comment by jasonjckn** [comment]
This is now fixed. See master.
